// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrito (Ctrl+B)',
italic_desc : 'Itálico (Ctrl+I)',
underline_desc : 'Sublinhado (Ctrl+U)',
striketrough_desc : 'Taxado',
justifyleft_desc : 'Alinhar a Esquerda',
justifycenter_desc : 'Alinhar ao Centro',
justifyright_desc : 'Alinhar a Direita',
justifyfull_desc : 'Justificar',
bullist_desc : 'Marcador',
numlist_desc : 'Lista',
outdent_desc : 'Identar a Esquerda',
indent_desc : 'Identar a Direita',
undo_desc : 'Voltar (Ctrl+Z)',
redo_desc : 'Refazer (Ctrl+Y)',
link_desc : 'Inserir/editar link',
unlink_desc : 'Deletar Link',
image_desc : 'Inserir/editar imagem',
cleanup_desc : 'Copiar Formatação',
focus_alert : 'A editor instance must be focused before using this command.',
edit_confirm : 'Você quer usar WYSIWYG para este textarea?',
insert_link_title : 'Inserir/editar link',
insert : 'Inserir',
update : 'Atualizar',
cancel : 'Cancelar',
insert_link_url : 'Link URL',
insert_link_target : 'Alvo',
insert_link_target_same : 'Abrir link na mesma janela',
insert_link_target_blank : 'Abrir link em nova janela',
insert_image_title : 'Inserir/editar imagem',
insert_image_src : 'URL da Imagem',
insert_image_alt : 'Descrição da Imagem',
help_desc : 'Ajuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
